### ISSUE TITLE
Loading images with prefetching

### ISSUE THREAD

**Issue by skoop12** [uchicago-mobi/MPCS51030-2019-Winter-Forum#103]
I'm trying to load the album images within the collectionView prefetchItemsAt method, and it works to asynchronously load the albums later in the collection, but not for the first screen of albums.  When I load the app the first ~20 albums keep the placeholder image, but if I scroll to the right I can see albums starting to populate with the correct images.  However, I have to scroll back to load the initial screen of images. If there is less than a full page of results returned the images never "prefetch" and load.  Is there another method needed to load the initial page of albums?

**Comment by hbennett766** [comment]
This is a great exercise in bug diagnostics. There are two main actions that need to happen here:

1. the image is fetched from the server
2. the UI is updated after the image is fetched

Because some of your images are appearing, I would guess that the images are fetching as expected. This sounds more like a UI bug to me. (educated guess, we'll figure out whether I'm right)

Double check that these two things are happening immediately after each image is fetched:

1. the correct cell's imageView.image property is being set to the image
2. this reload is happening on the main thread

Let me know if you need help doing either of those two things, and also what your findings are. Can you also push your latest code to your repo? I can check it out in person if this doesn't solve the problem.

**Comment by skoop12** [comment]
I think the correct cell's imageView.image property is being set because the images are right when they do load, but is there some other way to check that? 

The reload is happening within the completion that is within the Dispatch.main.async (I used the code from the slides), so I think that is happening on the main thread, but there could be something else wrong with my code there.

I've pushed my latest code if you want to take a look. The cell reloading and image getting is happening in lines 172 - 212 of the CollectionView.swift file.

**Comment by hbennett766** [comment]
Breakpoints are your best friend here. I'm starting by setting one on line 187. I chose this location because I can see whether the image is being added to `ablumViews`, and also what index the collection view thinks it should load.

Try setting that breakpoint at line 187 yourself, and then inside your debugger window, right next to `(lldb)`, type `po indexPath.row` then hit enter. This "print out" statement will tell us what row we are working with.

Also type `po albumViews[indexPath.row].albumImage` then hit enter. This "print out" statement will tell us, if the image is nil, that the image is not being added properly to the array, or if it is some sort of `UIImage` object, that it is correctly added to the array.

^ I'm about to do the same here. Checking to make sure the mechanics of your completion are working is an important first step. Sort of a gut check before we get into the more complicated possible issues.

**Comment by hbennett766** [comment]
Here's a screenshot of my initial findings. The red square indicates the "continue" button. After you're done printing out a statement, tap that to continue running the app. This breakpoint was hit multiple times in a loop, and each time, you can see I printed out the `indexPath.row`. It's pre-fetching for the collection view cells starting at index 20.

This lines up with the bug you described, because index 20 would be the 21st collection view item, on the second page.

<img width="914" alt="screen shot 2019-02-22 at 9 52 23 am" src="https://user-images.githubusercontent.com/10427644/53253789-a8ae7080-3687-11e9-8f52-85afe4c17408.png">

**Comment by hbennett766** [comment]
My second test was to add a print statement at line 185 as such:
```
self.albumViews[indexPath.row].albumImage = image
print(indexPath.row)
```
These were the results:

<img width="301" alt="screen shot 2019-02-22 at 9 59 07 am" src="https://user-images.githubusercontent.com/10427644/53254261-a4368780-3688-11e9-8c08-ec5a4664949b.png">

So it looks like I was wrong. This is in fact a fetching bug. The problem to solve here is how to load the images from index [0...19]. These are not loading right off the bat because you currently _only_ implement the `prefetchItemsAt` method. This method will only load images that are off screen. So currently, when you scroll to page 2, page 1 loads when it is off screen, and you see the images when they come back into the display.

Does the root of the bug make sense? A fix for this is to implement a separate call to fetch the first page images. Lmk if you need help doing this.

**Comment by skoop12** [comment]
Yes that makes much more sense! And thank you for demonstrating the breakpoints, I didn't know you could enter commands after breaking. I will implement another method to load the first 20 albums. Thank you!

**Comment by hbennett766** [comment]
Of course! Glad it was helpful. Breakpoint `po`s are a powerful debugging tool.

**Comment by susanstevens** [comment]
It sounds like this issue was resolved, but for anyone else reading this thread, I just want to mention that you don't have to use the `collectionView(_ collectionView: UICollectionView, prefetchItemsAt indexPaths: [IndexPath])` method for this assignment.

As mentioned in class, `collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell` is a perfectly good place to kick off a network request to download an image. This is one of the collection view datasource methods that closely matches a table view datasource method we've used previously.
