### ISSUE TITLE
What format are the images in?

### ISSUE THREAD

**Issue by michaelsoren** [uchicago-mobi/MPCS51030-2019-Winter-Forum#104]
I've got querying of the album artwork images working, but UIImage obviously isn't workable in the codable struct. When I try to print out the result of the search, I get "unable to print data". So essentially, what is the format of the return value from the URL search? Or alternatively, how could I see what the result is?

**Comment by hbennett766** [comment]
It sounds like you're using your artwork url to successfully get the data back from your image fetch. If that's the case, there is a handy image initializer that should help you out:

`let image = UIImage(data: <your data>)`

Does this help?

**Comment by susanstevens** [comment]
There's also a slide from the last lecture that shows what the completion block for your `URLSessionDataTask` should look like. It uses the `UIImage(data: <your data>)` constructor that Hannah mentioned.

Keep in mind that when your app first loads, you'll need to download JSON from the iTunes Search API url listed in the assignment write up. You'll convert that data into codable structs.

When you're fetching images, on the other hand, you'll use the url from the `artworkUrl100` field on the JSON. You'll need to create a second function in your service class specifically for downloading images. In this function, instead of converting the `data` object you get back into a codable struct, you'll convert it into a `UIImage`.
