### ISSUE TITLE
Understanding Apple documentation

### ISSUE THREAD

**Issue by ab1470** [uchicago-mobi/MPCS51030-2019-Winter-Forum#121]
I'm trying to work with date objects, but the official Apple documentation doesn't seem to match up with my experience in Xcode. 

From the [Apple documentation](https://developer.apple.com/documentation/foundation/nscalendar/1416814-nextdate), it looks like I should be able to do the following:

```swift
let calendar = NSCalendar.current
calendar.nextDate(after: Date(), matchingHour: 20, minute: 30, second: 0, options: .matchNextTime)
```
But when I try to do that in Xcode, the syntax above isn't an option:
<img width="945" alt="screen shot 2019-03-04 at 1 46 20 pm" src="https://user-images.githubusercontent.com/22333279/53758623-e67b7800-3e83-11e9-91d7-e715935ee13f.png">

I can get the result I want with:
```swift
calendar.nextDate(after: Date(), matching: DateComponents(hour:20, minute:5, second:0), matchingPolicy: .nextTime)
```
which is fine, but I'm wondering why I can't do it the way that's spelled out in the Apple docs. Is Apple not good about updating its documentation when Swift changes? Am I misunderstanding something?

**Comment by chelseatroy** [comment]
Hey Andew,

So interestingly, when I go to force it, I get:

<img width="746" alt="screen shot 2019-03-04 at 5 51 36 pm" src="https://user-images.githubusercontent.com/5744164/53771062-dc1ea580-3ea6-11e9-81dc-463f03330c41.png">

Conveniently, the Swift core stuff is open source, so we can see exactly why this happens. Looks like Philippe Hausler spent some time about 3 years ago deprecating some of the older Swift syntax. Here's your method in particular:

https://github.com/apple/swift-corelibs-foundation/blame/4b34eb54221ab0f1470d2cb4f1c7c7763089e5e3/Foundation/Calendar.swift#L813

The `@available` annotation in Swift allows developers (mostly the Swift team, but you could do this too) to only allow certain methods to be used with certain versions of the language. This allows them (and you!) to prevent developers on the new versions from using a deprecated thing without causing a backward-breaking change for developers on older versions.

**Comment by ab1470** [comment]
Interesting. Thanks for looking into it. 

So this means that the [Apple Documentation](https://developer.apple.com/documentation/foundation/nscalendar/1416814-nextdate) should mark that function as deprecated, correct? Does this happen a lot? In general, how reliable would you say the Apple Documentation is?

**Comment by chelseatroy** [comment]
**Short Answer:** 

Yes, it happens sometimes. In general, Apple's is as reliable as any other documentation, barring some outliers. 

**Long Answer, definitely out of scope for this class, feel free to not read this:**

When I'm trying to figure out how to use a piece of software, my sources, in rough order of priority, go:

**1. The tests of the code itself, if it is open source** (high legibility, high reliability, high speed of access)

**2. The implementation of the code itself, if it is open source** (dodgier legibility, high reliability, high speed of access)

In Swift in particular, legibility trends higher than some other code bases I've worked with.

**3. The documentation** (dodgy legibility, dodgy reliability, high speed of access)
- This is the one you asked about. As software projects get larger, it's hard for teams to keep every piece of documentation up to date. This is firstly because there is no direct connection between the code and the documentation (as there is for tests), and secondly because documentation on many developer teams is a second-class concern (which is unfortunate). I'd hesitate to make a blanket statement about the reliability of the Apple documentation. For any project, docs sometimes fall out of date. 

**4. Stack Overflow, askquestions.tech, or other results from googling my question** (dodgy legibility, dodgy reliability, high speed of access). 

Internet comment people can sometimes be right and save me hours of time. They can also sometimes be wrong and unkind to boot. For fast-changing APIs—and Swift's changes pretty fast right now—most of the questions on the internet will pertain to the way it _used_ to be before its latest iteration, since the tech has spent more time in all its previous iterations than its newest one. A good example of this is `UIView.animate` vs `UIViewAnimation`. The latter is the updated way, with many technical advantages. The former is the one you find on almost every StackOverflow post. 

Recommendation here: if someone on the internet helps you, it is nice to thank them. First of all, that lets other people know that this solution worked. Second of all, helping people on the internet can be pretty thankless sometimes, but we need people to do it, and thankfully for some reason people still do it. So it's nice to reward when they do. 

**5. The word of a developer advocate on how to do it** (high legibility, high reliability, medium speed of access). 

Dev advocates are paid to evangelize their software and help developer communities learn to use it. They're usually great communicators and very knowledgable about their product. I'll try to befriend one first thing when I start using a technology that has them. They're very busy, so it might take a while to get their answer. I'll sometimes ping them if I'm stuck and keep searching on my own until they get back to me.

**6. The word of a developer I trust on how to do it** (high legibility, dodgy reliability, high speed of access). 

I go to folks I know who _only_ (or mostly) write the thing I'm trying to write, and I ask for their opinion. They tend to respond well to this because we already have a relationship, and they tend to know what's going on. They _might_ not know the latest and greatest the way a dev advocate does. 

**7. The word of a core maintainer on how to do it** (dodgy legibility, high reliability, low speed of access). 

Not every project has dev advocates. Open-source ones often fall into this category. Sometimes I can access the writing (or ask questions) of the maintainers. Maintainers are usually overwhelmed. Maintaining an open-source project is a lot of work, and maintainers are usually fielding dozens to hundreds of complaints at a time from community members (often about software they wrote for free). As you can imagine, this is frustrating for them. Some maintainers make a rule of ignoring community requests so they can focus on the tool. If I do get a response from one, I run the risk that it might sound curt, or it might be unclear (unlike dev advocates, maintainers aren't necessarily great communicators, though sometimes they are.) I don't blame them, and I'm glad they're out here writing the thing I use, usually at no cost to me. But I don't depend on them for answers.

**And Finally**

If I had a devil of a time figuring out how to do something and then I finally succeeded, I try to write a blog post about what worked for me. Sometimes these posts take off ([which is how I learned that hundreds of people get gray hairs trying to do a card flip animation in Android](https://chelseatroy.com/2016/08/02/android-how-to-card-flip-animation-in-api-23/)). More importantly, it's a way to pay it forward. Our jobs would be a lot harder without those strangers on the internet helping us out along the way.

**Comment by ab1470** [comment]
Sorry for my late reply here, but thanks so much for this really thorough response! This is definitely helpful to know.
