### ISSUE TITLE
Passed type does not conform to expected type

### ISSUE THREAD

**Issue by lmnoel** [uchicago-mobi/MPCS51030-2019-Winter-Forum#124]
I have a class, UserPreferences, which has a constructor that accepts as a parameter a custom delegate, RefreshTableDelegate. The ViewController which instantiates UserPreferences conforms to RefreshTableDelegate in an extension.

instantiation:
`var userPreferences = UserPreferences(self)`

UserPreference's constructor :
`
init(_ delegate : RefreshTableDelegate) {
...
}
`

conforming to delegate:
`extension MasterViewController : RefreshTableDelegate {
...
}
`

The MasterViewController fully conforms to RefreshTableDelegate; however the instantiation of UserPreferences yields compiler error:
`Cannot convert value of type '(MasterViewController) -> () ->`

What is my issue? I am particularly confused because when I didn't set the delegate in the constructor, but rather after instantiation, there were no errors. Additionally, when I cast `self as? RefreshTableDelegate`, there is no compiler error but there is sigabort on instantiation.

Code is in MasterViewController.swift in my repo which is up to date. See line 32.

**Comment by chelseatroy** [comment]
Ah, yep. So the properties at the top of the class do not depend on an _instance_ of the class existing yet. However, `self` specifically refers to the instance of the ViewController. Until the ViewController is instantiated, there is no 'self.' As a result, the compiler thinks you are trying to pass in the class, rather than an instance of the class, to the model constructor. That's not the same thing as an instance, hence the message.

I got your app to work by declaring the variable userPreferences on line 32, but instantiating it with `self` in `viewDidLoad()` on the line immediately preceding `formatter = Formatter(userPreferences: userPreferences)`.

**Comment by lmnoel** [comment]
Great, thank you!
