### ISSUE TITLE
UIView.animate leads to offset rotation in TableViewCell

### ISSUE THREAD

**Issue by lmnoel** [uchicago-mobi/MPCS51030-2019-Winter-Forum#133]
I have a TableViewCell which has a rudimentary compass view (circle with a line pointing in some heading). Right now, it is hard-coded to 0 degrees (North). I am trying to implement an animation effect such that the line rotates back and forth around the direction it is pointing, but by no more than a few degrees. 
<img width="290" alt="Screen Shot 2019-03-10 at 20 12 42" src="https://user-images.githubusercontent.com/20692394/54094825-93b52b00-4371-11e9-9abc-6776d15890a6.png">

The problem is that when the cell exits the screen and then is later re-rendered, the rotation becomes offset (and is no longer centered on 0 Degrees/North.

<img width="289" alt="Screen Shot 2019-03-10 at 20 12 57" src="https://user-images.githubusercontent.com/20692394/54094859-c3fcc980-4371-11e9-907d-16d5969f05f2.png">

I override prepareForReuse, and call `setNeedsDisplay()` on the 'compass' view to force a redraw at the original heading, and yet the rotation still becomes offset. If this is hard to picture... launch my app, and you will notice it on the home screen. Why is the rotation becoming offset even though I am forcing the view to be redrawn in prepareForReuse?

**Comment by chelseatroy** [comment]
Hi Logan,

I'm not seeing the compass at all. Is the latest pushed?

<img width="369" alt="Screen Shot 2019-03-11 at 12 12 08 PM" src="https://user-images.githubusercontent.com/5744164/54139029-0a483c00-43f7-11e9-9677-5a7e7887b427.png">

**Comment by lmnoel** [comment]
Indeed, the latest version is pushed. Did you scroll to the end of the table view? It should be the last 3 cells.

**Comment by chelseatroy** [comment]
Ohhh, I see. OK One sec, I'll take a look

**Comment by chelseatroy** [comment]
Ah. So your issue is that, when you reset the view, you do remove the old _animations_, but you don't reset the existing _rotation_. So each time it animates, it's animating it off of the existing view's rotation, which is the rotation from each time * however many times you've scrolled the cell off and back onto the page.

I fixed this by:

a) Moving all of the heading logic into CompassView rather than the Cell (not strictly necessary, but much easier for another dev to understand this way)
b) each time we animate the compass, we save the amount we rotated by to an instance attribute
c) we add a didSet to compassHeading that rotates the view _back_ by the amount in the instance attribute

Happy to go through this with you, and will open a branch PR to show you what I did. This solution is not the ideal, refactored version—you'll see that we have a lot more variables going on now than we need. So I'd expect you to clean that up in your final version.

**Comment by chelseatroy** [comment]
OK branch pushed. It's called `fix-compass-rotation-persistence`.

**Comment by chelseatroy** [comment]
This also fixed the other issue which I'm sure you noticed, which was that the animation stopped happening after the first off-and-on scroll. A good example of how logic organization can fix—or cause—multiple headaches at once ;)

**Comment by lmnoel** [comment]
Thank you so much for taking a look! I think I was assuming that my previous implementation was calling the compass's `draw()` whenever I called `setNeedsDisplay`, so I didn't think I had to rotate the heading back to the origin. It seems that is not what happens?

And does the compass need to transform by goBack because the rotation (when reused) is now compassHeading + degreesOfMovement? I assumed the .autoreverse option meant that the "actual" rotation would stay at compassHeading.

Finally, I notice that the compass freeze is fixed whenever `prepareForReuse` is called, but I observe that `prepareForReuse` is *not* called when I tap a cell to enter a detail view, and then tap `Back` to return to the TableView--and so, the animation freezes. Do I need to somehow check if the "Home" View is redrawn, and if so call `.animateCompass` on all cells?

**Comment by chelseatroy** [comment]
> I think I was assuming that my previous implementation was calling the compass's draw() whenever I called setNeedsDisplay, so I didn't think I had to rotate the heading back to the origin.

In fact, it is! _But_, that doesn't set the _compassHeading_ variable back to zero, and neither does draw(). We're still working with an instantiated `CompassView` whose compassHeading is whatever we previously set it to. 

> And does the compass need to transform by goBack because the rotation (when reused) is now compassHeading + degreesOfMovement? 

Exactly :)

> I assumed the .autoreverse option meant that the "actual" rotation would stay at compassHeading.

Nope - what `autoreverse` does is it makes your _animation_ go back and forth, but not the value of `compassHeading` itself.

> What exactly is going on with didSet? I haven't seen that before.

Yep—I'm cheating by using that because we didn't cover it in class ;). But it is a (in my opinion) pretty brilliant Swift feature. [Here's more on didSet and willSet, for your perusal](https://medium.com/the-andela-way/property-observers-didset-and-willset-in-swift-4-c3730f26b1e9).

> Finally, I notice that the compass freeze is fixed whenever prepareForReuse is called, but I observe that prepareForReuse is not called when I tap a cell to enter a detail view, and then tap Back to return to the TableView--and so, the animation freezes. Do I need to somehow check if the "Home" View is redrawn, and if so call .animateCompass on all cells?

Yes—`prepareForReuse()` is called when a cell that has scrolled _offscreen_ is about to come back _onscreen_. It's a method that assists the iOS Framework in recycling views, a technique that modern mobile frameworks use to reduce the number of objects allocated for an app at any given time. The idea is that the app only instantiates as many of the cells as fit on screen, rather than instantiating one for every item in your list. When one cell scrolls offscreen, the framework prepares it to be reused to display the data in the _next_ item that is about to scroll _onscreen_. So cells work like a conveyor belt rather than a continuous line of items. 

If you put a print statement in your `prepareForReuse()`, you will notice that it is called only when a previously offscreen `WindStationTableViewCell` is about to scroll onscreen. It is not called when navigating to and from the detail view. So indeed, you need to make sure that animation is still happening upon navigating back.
