### ISSUE TITLE
Faster Image Download? 

### ISSUE THREAD

**Issue by eealexander2** [uchicago-mobi/MPCS51030-2019-Winter-Forum#146]
Hello! Part of our app includes showing images of items (much like how Airbnb shows images of homes). So far, it's working, but it's pretty slow and not a super great user experience. Is there a way to speed up image download? What's the best way to approach this? Thanks in advance!

**Comment by chelseatroy** [comment]
Hi! Where are you pulling the images from, and how are you pulling the images now? 

I am happy to take a look (though I'd need the remote for your repo to do that, since it's not under your github name). 

In general, there are some encoding formats that are faster than others for image download. I have had a lot of success with base64 encoding images for transfer over HTTP.

It's also possible that you're loading up an unnecessarily large or detailed image and then resizing it to a smaller size that doesn't require so much detail. My recommendation in these cases is to check the size and resolution on the images you're sending and see how that compares to the image size at display time. 

Does this make sense?

**Comment by eealexander2** [comment]
Thanks! Yeah the frontend captures the data, and we call imageData.base64EncodedString(), then send to rails. From there, Rails does: 

`data = StringIO.new(Base64.decode64(params['image-data']))` , and sending it to S3. When I look at it in S3, the image is super huge. I am guessing there's a way to shrink it down before sending to S3?

**Comment by chelseatroy** [comment]
Ahhh.

OK so two things could be going on here.

1. The image is bigger than you need it to be. Sounds like that's the case. For that I'd resize the image on the client (the iOS app) to the size you'll need there, then send that up (so that you save both the upload call and the download call from an unnecessarily large payload). 

A note on this: if your app is meant to work on an iPad, pick the smallest image size/resolution that looks good on an iPad. The image will appear larger on an iPad than on a phone, so you could shrink/convolute the image too much so that it looks fine on a phone but pixelated on an iPad. To resize image in Swift:

```Swift
        let userImage = UIImage(named: "hugeImage")
        let newSize = CGSize(width: 100.0, height: 100.0) \\ max size you need it to be to look good
        userImage?.draw(in: CGRect(x: 0, y: 0, width: newSize.width, height: newSize.height))
        UIGraphicsBeginImageContext(newSize)
        let resizedImage = UIGraphicsGetImageFromCurrentImageContext();
        UIGraphicsEndImageContext();
```

2. You're sending an image to Rails, which then sends it to s3. So the image has to go over HTTP twice to be uploaded, and then (I'm guessing) twice again to be downloaded: Rails asks for the image from s3 and then loads it into the response payload for the iOS app. 

There's also the fact that base 64 decoding in Rails in particular is kind of slow. Not "don't use it" slow, but slow enough that this might be hanging you up a little, especially if the image is huge.***

You could cut the time by giving rails the s3 location of the image rather than the image itself, letting Rails send that in its response to the iOS app, and download the image straight from that s3 location on the client. 

This would mean integrating with AWS from the iOS app, which I remember was causing some issues for y'all, so if you want to leave the double-pass through Rails in place I'd first try resizing the image as described in #1 and see if that brings the call time down to an acceptable length for you. 

\***  I have seen one project deal with this on a Rails server by shelling out base64 decoding to C using the `ffi` gem ([here's the github for that](https://github.com/ffi/ffi)). We did it because we were sending health insurance cards over the wire, and the resolution had to be high for the tiny fine print on the back. I think this is overkill for your use case, but I mention it so you know another option at your disposal.

**Comment by eealexander2** [comment]
Thanks! I will try this out.
