### ISSUE TITLE
No need to add "permission to access the photo library?

### ISSUE THREAD

**Issue by JohnReddyZhang** [uchicago-mobi/MPCS51030-2019-Winter-Forum#15]
So the tutorial assumes the app will crash after first compilation because I did not give permission to access to photo library, but this was not my case. I could just access the simulator's photo library without app crashing even though I did not add the permission line in `info.plist`. Is this normal?
Thank you very much!

**Comment by hbennett766** [comment]
Prior to iOS 11, the photo picker had read-only access to the entire photo library when the picker was displayed. As of iOS 11, instead of the app seeing the user's photo library when they go to select an image, the photo picker runs as a separated process from the app. When the user explicitly chooses a photo, _then_ and only then does the app get read-only access, to that one photo. Because of this update, the photo picker does not need photo library permissions.

**Comment by hbennett766** [comment]
For the sake of this assignment, you should still include the permissions logic. To help with testing this, [set the minimum deployment target](https://stackoverflow.com/questions/46465408/swift-4-setting-a-minimum-deployment-target) to iOS 10, and then also run iOS 10 on the simulator.

**Comment by JohnReddyZhang** [comment]
Got it, thanks!
Should I also set minimum deployment environment to 10 in submission?

**Comment by hbennett766** [comment]
You can if you want to, that would help our testing! But, you will not be penalized if you don't. That's an easy toggle for us to adjust on our side.
