### ISSUE TITLE
Going back to main controller after delegate function finishes

### ISSUE THREAD

**Issue by liuwinshen** [uchicago-mobi/MPCS51030-2019-Winter-Forum#151]
I have two view controllers: Landing and Log In. The Landing VC needs to know when someone has logged in, then segue to another view controller. 

**What I have so far:**
Landing VC has a LogInDelegate protocol defined
Landing VC calls its delegate then segues to another view
Log In VC is set as the delegate, follows the protocol, and is running the delegate's function properly

**Problem:**
Once the Log In VC's function completes, it does not call the `prepare(for segue)` method. Thus I stay stuck on the Log In VC and can't go back to the Landing VC.

How do I leave the delegate and go to the next VC?

**Comment by liuwinshen** [comment]
Actually, I got back to the Landing VC but don't know how to automatically segue to the next view controller from there. 

What I'd like to do is have the user:
1. See the landing screen when they open the app
2. Press "Log In" which presents the log in screen modally
3. Upon successful log in, dismiss the log in screen and segue to a Tab Bar VC

Is it proper to use a delegate from Landing to Log In and then have the Log In VC segue straight to the Tab Bar VC?

**Comment by susanstevens** [comment]
If you’re looking for a way to programmatically trigger a segue to a new view controller, the performSegue method should do it! https://developer.apple.com/documentation/uikit/uiviewcontroller/1621413-performsegue

You can add the segue in storyboard from one view controller to another (instead of from a button or cell to a view controller). And you’ll need to give it an identifier in storyboard so that you can refer to it in code.

I’d say it’s up to you whether you want this segue to go from the login screen to the next screen, or from the landing screen to the next screen. I can imagine either option working.

**Comment by liuwinshen** [comment]
I had that after my delegate function was called but the segue wasn't being performed...That's okay. I'll use the other option of going from the login screen to the next one instead of having the landing screen do it. Thanks!
