### ISSUE TITLE
Trigger a refresh when settings change

### ISSUE THREAD

**Issue by ab1470** [uchicago-mobi/MPCS51030-2019-Winter-Forum#153]
I have a settings view controller that appears modally over my main view controller. When a user changes some settings and dismisses the settings modal, I need to call several functions on the main view controller to refresh the models and update the views. The functions are already defined in the main view controller.

I think this is probably best implemented through delegate/protocol, but I wanted to check here before I spend a bunch of time implementing it. Would notification center be useful here?

```Swift
@IBAction func settingsDismiss(_ sender: UIButton) {
    saveHourMinToDefaults(leaveHomeTimePicker.date, RouteTitle.fromHome)
    saveHourMinToDefaults(leaveWorkTimePicker.date, RouteTitle.toHome)
    dismiss(animated: true, completion: nil)

    // Code to trigger a refresh of TripViewModel (i.e., call trip.updateCommuteTimes)
    // Code to trigger a refresh of weather data (i.e., call trip.updateWeather)
    // Code to trigger a refresh of GraphView (i.e., call graphView.updateGraph)
}
```

**Comment by susanstevens** [comment]
This seems like a great use-case for delegates! You have two view controllers that need to talk to each other, and since one is presented on top of the other, it should be easy to set up a delegate. I usually reserve Notification Center for the (very rare) situation that one component needs to broadcast a message to multiple components OR the two components that need to talk to each other are far away in the object hierarchy.

**Comment by ab1470** [comment]
Thanks!
