### ISSUE TITLE
Reusable content

### ISSUE THREAD

**Issue by ab1470** [uchicago-mobi/MPCS51030-2019-Winter-Forum#154]
I have a view controller that shows similar information with similar formatting in two places. Basically, the top half of the VC shows information about a morning commute, and the bottom half shows information about an evening commute. Each commute section shows information about weather conditions, departure time, and a line graph. 

What's a good way of designing one "commute" template that can be used twice? Should I implement a two-cell table view, and design my commute template as a prototype cell? Or what about designing the commute content as a .xib file, and placing the nib twice on the VC page? Are there any other good approaches?

**Comment by hbennett766** [comment]
Nice work making this connection. "Multiple of the exact same view structure = reusable view". Great architecture!

I don't think a table view is the way to go here. A table view is more geared toward "many" rather than two, and also toward changing amounts of data objects, which you don't have.

I would personally use the xib approach. Or in generalized terms, the "single reusable view" approach. Once the two views are placed on the screen, your customization is as simple as injecting the commute views with the information needed.

A second approach that would also work is using a container view. Here's a good resource on what that approach would look like in practice:

https://useyourloaf.com/blog/container-view-controllers/

My hesitation with the container view approach is that you toe the "over-programming" line. Container views are tailor made for two disparate views on the same screen. Your views are identical in structure, and the same effect can be achieved at lower programming cost with your xib idea.

**Comment by ab1470** [comment]
Thanks! Now I have an extension of the question.

See my crude mockups below. The first one, in the commute tab, shows what I was talking about above. I want to reuse the entire "To Work" and "From Work" commute views, and I'll probably do that as a nib, as you suggested. But on a map view, I may want to reuse _only_ the graph that's within the To Work/From Work nib, as shown in the bottom mockup. Are nested nibs allowed? My thought is that I would make a graphView.xib, and nest it within a commuteView.xib for the To Work/From Work views.

If I were to follow the nested nibs approach, I'm wondering how to handle the delegates so that I can update the graph. Does the following make sense?
* **In CommuteViewController:** commuteView.xib is a delegate of CommuteViewController. graphView.xib a delegate of commuteView.xib
* **In MapViewController:** graphView.xib is a delegate of MapViewController

![Untitled-1Artboard-1](https://user-images.githubusercontent.com/22333279/54620054-9976d480-4a33-11e9-8811-c21b99782394.png)
![Untitled-1Artboard-2](https://user-images.githubusercontent.com/22333279/54620055-9976d480-4a33-11e9-9c8c-4d775b118134.png)

**Comment by hbennett766** [comment]
Nested xibs are definitely allowed. "Black boxing" each unique object is good practice, so having a "graph view" that is its own entity, and lives inside both the "commute view" and the "map view" works just fine.

If you don't want to nest xibs, the container view approach for the CommuteViewController would slide up to your best option. Since the commute views would now be commute view controllers, you'd only have one level of "views" instead of two.

The delegate setup is a more complicated question. The answer revolves around "what communication do you need to accomplish?", and "how can you accomplish that communication with as few 'phone calls' as possible?", where 'phone call' refers to 1 level of delegate call.

In general, a view or view controller should only communicate with an object "1 level" from itself. For example, there should not be direct communication from the graph view to the commute view controller, and vice versa. What you've outlined follows that rule.

**Comment by ab1470** [comment]
Very helpful. Thanks!
