### ISSUE TITLE
How to create target-action when action requires parameter

### ISSUE THREAD

**Issue by liuwinshen** [uchicago-mobi/MPCS51030-2019-Winter-Forum#22]
The examples for target-action from lecture only have functions that don't require parameters and the StackOverflow examples haven't made sense to me.

Is there a way to set up target-actions on a button when the action requires parameters. For example, instead of `button.addTarget(self, action: #selector(displayFireworks), for: .touchUpInside)`, what's the best way to achieve: 
`button.addTarget(self, action: #selector(displayFireworks(color: red), for: .touchUpInside)`?

**Comment by susanstevens** [comment]
The `addTarget` method will accept selectors with one of these three function signatures:

```swift
@objc func doSomething() 
@objc func doSomething(sender: Any)
@objc func doSomething(sender: Any, forEvent event: UIControl.Event)
```

Here's what the selector would look like in each case:

```swift 
#selector(doSomething)
#selector(doSomething(sender:))
#selector(doSomething(sender:forEvent:))
```

If you try to use a function with a UIColor as one of it's parameters, you'll get an "unrecognized selector sent to instance" error at runtime. The button will always try to pass itself (the sender) as the first parameter if there is one, and since UIColor and UIButton are different types, your app will crash.

**Comment by liuwinshen** [comment]
Thanks, @susanstevens. Given `addTarget` is not an option, how do we create actions from functions that have parameters? Is there a pattern that can get UIColor to the button in this case, where the button is not in the interface builder?

**Comment by susanstevens** [comment]
If you want to change the text color or background color of the button, here's how you would do it:

```swift
button.setTitleColor(UIColor.red, for: .normal)
button.backgroundColor = UIColor.gray
```

Keep in mind that `addTarget` is only used to tell the button what function to invoke when the user interacts with it. It's not used the customize the appearance of the button.

Let me know if that answers the question!
