### ISSUE TITLE
How to ensure app doesn't crash if releaseDate? is null?

### ISSUE THREAD

**Issue by jbreynier** [uchicago-mobi/MPCS51030-2019-Winter-Forum#48]
Hello,

My app works and I'm able to display the release dates for all the movies, but I was testing out if the release date was null and I can't seem to find a solution for it:

![image](https://user-images.githubusercontent.com/46587690/52013462-c03c7400-24a2-11e9-9a5f-d8fa444f9a4b.png)

For the other values, I simply used the "??" function, such as:
`genreLabel.text = "Genre: \(currentMovie?.primaryGenreName ?? "No genre available")"`

But for the date, since we have to use the dateFormatter, I don't really know how to do it. I've tried the guard function, but I keep getting a lot of errors. 

Thanks!

**Comment by hbennett766** [comment]
We've got two optionals to consider here.

1. the input string
2. the date object created by the first formatter

The way you're handling `let date = formatter.date(from: testDateString ?? "")` isn't quite right, because we can't make a date out of an empty string, and shouldn't bother trying.

That date object is your second optional here, and being force unwrapped in your final line, which is also not quite the right approach. It's relatively negligible data. We want our app to still function if that release data doesn't exist.

What about using a set of chained `if let` statements? That provides the added bonus of an `else` clause to give your label text a default value, "Release Date: Unknown".

`if let testDateString = testDateString, let date = formatter.date(from: testDateString) {`

**Comment by jbreynier** [comment]
That worked, thank you!
