### ISSUE TITLE
rounded corner after draw function

### ISSUE THREAD

**Issue by jannydiu** [uchicago-mobi/MPCS51030-2019-Winter-Forum#52]
I tried adding a line in the infoview class after function awakefromnib. The line did show up, however, both the original corner and rounded corner also showed up. Does anyone know why it works this way? Although not required in the assignment, what should I do if I want to add a line in the infoview?

**Comment by susanstevens** [comment]
When you say both the original corner and the rounded corner appear, do you mean on your `InfoView` itself? If you're adding a sublayer to your `InfoView`, you'll need to set the corner radius of both the root layer and the sublayer. Otherwise, the sublayer might have rounded corners, while the root layer does not.

I'm not quite sure how this relates to drawing a line. But if you're trying to create a horizontal line between the text and the button, similar to what's shown in the screenshots on the assignment write-up, you might find it easiest to create it with a `UIView` whose height is set to 1 or 2 points.

**Comment by susanstevens** [comment]
I was just able to reproduce this issue. Just like you said, when you set a layer's `cornerRadius` _and_ implement the `draw` function, the `cornerRadius` will no longer be respected. 

The solution (which I found [here](https://stackoverflow.com/questions/7078911/uiview-layer-rounded-corners-and-drawrect/7391922)) is to set the layer's `masksToBounds` property to **true**. You can do this in `awakeFromNib()` where you set the other properties of the layer. According to Apple's [documentation](https://developer.apple.com/documentation/quartzcore/calayer/1410896-maskstobounds):

```
When the value of this property is true, Core Animation creates an implicit 
clipping mask that matches the bounds of the layer and includes any corner radius effects.
```

In this screenshot, I'm drawing a red line in the `draw` function and setting the `cornerRadius` in `awakeFromNib`:
![simulator screen shot - iphone 8 - 2019-02-09 at 14 37 58](https://user-images.githubusercontent.com/10423328/52526280-ed93d980-2c7b-11e9-8dd9-e844afdb9344.png)

And here is what it looks like when I add `layer.masksToBounds = true` in `awakeFromNib`.

![simulator screen shot - iphone 8 - 2019-02-09 at 14 38 11](https://user-images.githubusercontent.com/10423328/52526285-f4bae780-2c7b-11e9-9c1e-e30643aefae4.png)
