### ISSUE TITLE
frame.intersects(frame) has unexpected results

### ISSUE THREAD

**Issue by lmnoel** [uchicago-mobi/MPCS51030-2019-Winter-Forum#54]
In my view controller, I loop through an outlet collection of square views as suggested in the assignment. The squares are in logical order in the "view controller scene". In the IBAction outlet for my  x player tile's (xTile) UIPanGestureRecognizer, I loop through each of the 9 squares and print the indices of squares that intersect xTile. However, the intersection does not operate as expected: for example, no intersections are recorded when my xTile crosses the lower row of 3 squares; and intersections do not match the ordering of the tiles in the View Controller Scene when they are recorded.

Let me know if I have been unclear or can clarify anything!

**Comment by susanstevens** [comment]
It sounds like you're on the right track. Are your 9 squares all at the same level in the view hierarchy as your xTile? In other words, do they have the same superview? (Since `frame` based on the coordinate system of the superview, it's easiest if they share a superview.)

If that's already the case, you could also try printing out the frame of each square as you iterate through them. Print out the frame of the xTile as well and check if you see anything unexpected. That might give us some more information for debugging.

**Comment by lmnoel** [comment]
That was the problem, thank you: I had them at different levels in the view hierarchy
