### ISSUE TITLE
Animate the piece on activation using CASpringAnimation and UIViewPropertyAnimator

### ISSUE THREAD

**Issue by JohnReddyZhang** [uchicago-mobi/MPCS51030-2019-Winter-Forum#63]
I am trying to implement the adding an animation part of Starting of a turn and I am thinking about using SpringAnimation as shown in CoreAnimationDemo. However it seems that the implementation in the demo is not using UIViewPropertyAnimator as learnt in class. 
What I want to do is implementing a function `turnStarts` that gets called when a new player is starting its turn (initially in `viewDidAppear`) and in that func there should be an animation that makes the selected player pop in scale. However I don't know how to get the animation to work...
Here is the code of `turnStarts`
```swift
// MARK: Start of a turn
    func  turnStarts(for player: UILabel){
        let animationLayer = CAShapeLayer()
        
        player.alpha = 1
        let springAnimation = CASpringAnimation(keyPath: #keyPath(CALayer.transform))
        springAnimation.valueFunction = CAValueFunction(name: CAValueFunctionName.scale)
        springAnimation.fromValue = 0
        springAnimation.toValue = 1
        springAnimation.duration = 0.5

        animationLayer.add(springAnimation, forKey: nil)
        
        player.layer.addSublayer(animationLayer)
        
    }
```

And in `viewDidAppear`:
```swift
    override func viewDidAppear(_ animated: Bool) {
        turnStarts(for: PlayerX)
    }
```

in `viewDidLoad` I have set two Player Label's alpha to 0.5, by  `viewDidAppear` calling `turnStarts`, the alpha did change, but there was no animation, also the implementation was not in the fashion of UIViewPropertyAnimator... 
A way of implementation I could think of changing the scale a bunch of times using a series of UIViewPropertyAnimator, but that does not look like a good idea. 
Could you give me some suggestions on the implementation of that? Thank you very much!

**Comment by hbennett766** [comment]
I have never personally used `CASpringAnimation`, so I'm heavily relying on outside resources for this. It looks like you may have some extra layers in there? I think you can just add the `springAnimation` as such:

`player.layer.add(springAnimation, forKey: <some keyPath>)`

I found this medium article on core animations that knows more than I do. Lmk whether this is helpful. I'm learning this morning too!

https://medium.com/@joncardasis/better-ios-animations-with-catransaction-72a7425673a6

**Comment by JohnReddyZhang** [comment]
Thanks for the answer! However, I am still confused with this because directly adding the animation like that caused my app to crash... Could you explain what is "forKey" and "keyPath" in the implementation? I went through a few answers and documentations but did not quite get that... Thank you!

**Comment by hbennett766** [comment]
Yeah, that's a good question, it's a little weird and clunky.

The params `forKey` and `keyPath` both take object type `String`. That string is the string representation of the property you are trying to adjust with your animation.  It's of type `String` because of legacy code, long story short. Obj-C doesn't have Swift enums, and it also uses Key Value Observing (KVO) to do the animations.

Here's a little write up by Apple on the different animations you can do with that string literal key path.
https://developer.apple.com/documentation/quartzcore/cabasicanimation

Being able to type whatever string literal you want in that param, with no compiler-side checking to see if it's a valid property, seems like a bad idea. It is. So Swift came up with `#keyPath()`, which gives us some compiler feedback on whether that key path is actually valid. You did the right thing by using it.

In your implementation, those key paths need to match. Why? Not exactly certain, but I would guess it's because of the Key Value Observing that `Core Animation` is doing to be able to fire off your animation. It needs the key path of the animated object to line up with the key path of the animation? Again, educated speculation on the reasoning.

**Comment by JohnReddyZhang** [comment]
Thanks for the answering! I will look into that!
