### ISSUE TITLE
“Switching" players (using enum)

### ISSUE THREAD

**Issue by JohnReddyZhang** [uchicago-mobi/MPCS51030-2019-Winter-Forum#68]
Hi all,
In my implementation, I have a enum of `Player` in Grid and a property `var currentPlayer: Player?` in ViewController so that I could track which player is currently playing. However, at some point of the turn I want to switch the player from one to another. Is there a built-in way to achieve this "switching" effect using enum? Thank you very much!

for reference, here is my `Player`:
```swift
enum Player: Int {
    case O, X
}
```

I wonder if there is some convenient way of setting the `currentPlayer` to another...

**Comment by JohnReddyZhang** [comment]
I now have an idea is to implement this function in `ViewController` but that does not seem right:
```swift
    // MARK: switching player
    func switchPlayer() {
        if currentPlayer == .X {
            currentPlayer = .O
        } else {
            return
        }
    }
```

**Comment by hbennett766** [comment]
Enums are a powerful tool in Swift, good question. There are a couple things to address here.

First, it's not mandatory that you have an `else` half of an `if` statement. If you don't need it, don't write it. This method would function exactly the same written as such:
```
func switchPlayer() {
    if currentPlayer == .X {
        currentPlayer = .O
    }
}
```

Second, this only sets one half of the time. Currently, nothing happens if .O is the current player. To handle both cases, your `if/else` block would look like this:
```
func switchPlayer() {
    if currentPlayer == .X {
        currentPlayer = .O
    }
    else { // currentPlayer == .O
        currentPlayer = .X
    }
}
```

You can switch through Swift enums using the keyword `switch`. Here's what it looks like in action:
```
func switchPlayer() {
    switch currentPlayer {
        case .X:
            currentPlayer = .O
        case .O:
            currentPlayer = .X
    }
}
```

Swift also has the concept of a ternary conditional operator. It takes the form of:

`condition ? resultA : resultB`

where `condition` is a `Bool`. If `condition` is true, `resultA` will happen. Otherwise, `condition` is `false`, and `resultB` will happen.

The ternary conditional operator is shorthand for an `if/else` statement:
```
if condition {
    resultA
}
else {
    resultB
}
```

Check it out in action with your enum.
```
func switchPlayer() {
    currentPlayer = currentPlayer == .O ? .X : .O
}
```

The if/else block, the switch statement, and the ternary conditional operator all do the _exact_ same thing. It's up to you as a developer which one you think is the best option for this situation. Remember to keep best practice in mind. Clear and concise code is always a good thing!
