### ISSUE TITLE
Animations only running once

### ISSUE THREAD

**Issue by Celiajm** [uchicago-mobi/MPCS51030-2019-Winter-Forum#70]
All of my animations only run once. If I press the information or okay button again, nothing happens after the initial animation. The same thing is happening with my rotating pieces, they rotate on their first turns, and then don't rotate again after. Did anyone else have this issue?

**Comment by susanstevens** [comment]
This is a somewhat counter-intuitive aspect of `UIViewPropertyAnimator`. Once you've created an animator and started it, you can do things like pause and resume it, but you cannot re-run it from the beginning after it's completed. This means you'll need to create a new property animator each time you want an animation to run.

**Comment by Celiajm** [comment]
Ok, I remember seeing that for UIViewPropertyAnimator, but for my rotations I'm just using UIView.animate. Does this have the same issue?

**Comment by susanstevens** [comment]
`UIView.animate` is a bit different, since it doesn't return an `animator` property. You should be able to call it multiple times and have it perform the animation each time.

After you rotate the view, are you setting it back to the original rotation with `CGAffineTransform.identity` at any point? If not, try doing this in the completion block of your animation. If your view has already rotated once and you ask it to rotate to the same angle a second time, you won't see anything change on screen unless you've set it back to the original rotation first.
