### ISSUE TITLE
WKWebView never finishes loading

### ISSUE THREAD

**Issue by skoop12** [uchicago-mobi/MPCS51030-2019-Winter-Forum#74]
I have added a UIActivityIndicator to the DetailViewController and am trying to make it stop animating when the web page has finished loading, but the page never seems to finish loading.  The activity indicator is showing on the screen and starts animating when the webView didCommit function is called, but the didFinish function is never getting called.  The webpage loads on the screen and the activity indicator just keeps spinning, then it ultimately throws an error  `Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service`.  I've tried researching this error but can't figure it out. Do you have any idea what could be causing this?

**Comment by hbennett766** [comment]
What is the URL you are trying to load in the web view?

**Comment by skoop12** [comment]
It's trying to load the URL of whatever article is clicked. I printed the URL's for debugging (one example: https://www.wired.com/story/ideas-molly-wood-apple/). The page does show up in the view, so that part is working. It just never stops loading and then throws that error after a minute or so.

**Comment by hbennett766** [comment]
First thing to check: Presumably you have an instance of a `WKWebView`, let's say it's called `webView`. Verify that `webView` is being declared as a **_class level property_**. If it is an instance within a method, `webView` will be deallocated as soon as you reach the end of the method. This would mean that by the time `webView` is done loading, `webView` no longer exists, and that completed callback has nowhere to go.

```
let webView: WKWebView!

override func viewDidLoad() {
    webView = WKWebView(<some initializers?>)
    // do some stuff
}
```

Lmk whether this was your issue.

**Comment by skoop12** [comment]
Hmm yes I have it as a class level property (my code looks something like yours) and it's still throwing the error.

**Comment by hbennett766** [comment]
Can you double check your code against the Apple docs for `WKWebView`? Try setting up your code exactly like their example. Could be some minor out-of-order or missing piece.

https://developer.apple.com/documentation/webkit/wkwebview

**Comment by skoop12** [comment]
I commented out everything in my code for that class except for exactly what is on the apple developer website. When I click a on an item in the tableview it navigates to the webview and loads, and it reloads if I click on another table cell, but after a minute or so the same errors pop up... Could this error be related to another view or class's code? I'm very confused at this point.

**Comment by hbennett766** [comment]
![giphy](https://user-images.githubusercontent.com/10427644/52873516-cd00cf00-3114-11e9-8daa-e10b9a95ce5a.gif)

**Comment by hbennett766** [comment]
Hmmmm this is very weird. I'm out of ideas for what could be going wrong, but I can look at your project firsthand and try to figure this out. Can you email me your current project at hbennett766@gmail.com? If it's too large to zip and email, just push to one of the old assignment repos, 1, 2, or 3? I don't think the assignment 5 repo is up yet.

**Comment by hbennett766** [comment]
For anyone else having this issue: 

The infinite spinner was happening because the web view's delegate wasn't being set, and was unrelated to the console error message.

I never figured out how to get rid of the console message. I did find a bug report on this from iOS 11, so I'm assuming it's just never been fixed. It does not on its own negatively affect the app functionality.

**Comment by tpiske22** [comment]
I'm having the same problem. How did you get the webView delegate to set? I can't get mine to, so pages aren't loading.

**Comment by susanstevens** [comment]
@tpiske22 You can set the delegate for the web view in your view controller's `viewDidLoad()` method. Note that you'll want to use the `navigationDelegate` property. WKWebView also has a `uiDelegate`, which you don't need for this assignment.

If you're having trouble loading the pages, it probably isn't a problem with the delegate, though. Are you calling the web view's `load(_ :)` method and passing in a valid URL?

**Comment by tpiske22** [comment]
My web view's navigation delegate is set to self in viewDidLoad(), and my detail view controller is conforming to the WKNavigationDelegate protocol. I'm then calling load() with what seems like a valid URL. Before attempting the load(), I print out the URL. Here's some of my console output with the print and error.

loading Optional(https://www.engadget.com/2019/02/01/apple-google-internal-ios-apps-data-tracking/)
2019-02-17 21:54:42.667200-0600 CeaselessDischargeNews[20741:1666170] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

The annoying thing is, I initialize the url to be "www.apple.com", as a default. Whether or not my web view's delegate is set, apple.com pulls up on the initial detail view. When I hit a table view cell after that to load a new page, I run into this error. Another thing - my activity indicator isn't appearing onscreen, despite the page loading for a solid 10 seconds before giving up.

**Comment by susanstevens** [comment]
By default Apple blocks http urls since they are not secure. Https urls should work fine, though. It looks like they changed the console warning that appears when you try to load an http url. It used to be a bit more decipherable, and it would suggest that you change a setting in your Info.plist to allow http urls. My guess is that Apple removed this because they are now discouraging people from using http urls at all.

For the assignment, one option is to just show your error message to the user when they select an article with an http url. If you want to allow http urls, you can change your Info.plist to match the below. (This may also help with debugging your activity indicator.) The selected lines are what you would need to add.

<img width="903" alt="screen shot 2019-02-18 at 7 30 02 am" src="https://user-images.githubusercontent.com/10423328/52954503-01ac9a80-3350-11e9-838e-7af5d2348caf.png">

**Comment by susanstevens** [comment]
Oh wait, it looks like you actually are using an https url... I'm not sure why that would be blocked or timing out. I'm able to get the url https://www.engadget.com/2019/02/01/apple-google-internal-ios-apps-data-tracking/ loading fine in a web view, so it must not be an issue with the url itself.

If you hardcode url so that it loads www.apple.com every time you tap on a table view cell, does that work? I'm wondering if it's something about how the web view is loading after tapping on a table view cell...

**Comment by tpiske22** [comment]
Actually yeah, it does work to hardcode apple.com. Hmmm...

**Comment by lmnoel** [comment]
I'm having the same issue. I think it's because sandboxing is enabled by default for newer versions of xcode: https://forums.developer.apple.com/thread/92265

I can't seem to find the option to turn it off in Xcode 10.1, though

**Comment by susanstevens** [comment]
I'm also using Xcode 10.1. I just checked my console output, and I'm actually seeing the same warning, but it doesn't seem to be preventing the articles from loading in the web view.

If either of you want to push up your projects, I can pull them down later tonight and take a look. I'm guessing this console warning is a red herring, though, and there's actually something else preventing the articles from loading.

**Comment by lmnoel** [comment]
pushed

**Comment by tpiske22** [comment]
Me too. Thanks for the help. I'll let you know if I figure something out.

**Comment by JohnReddyZhang** [comment]
I am getting similar issue when loading a techCrunch url which is actually https, then I used the changing `info.plist` and it works now. Then I changed the property to `NO` and it still works. Weird.

**Comment by susanstevens** [comment]
@lmnoel and @tpiske22 I downloaded both of your projects, and the articles are loading in the web view for me. The only ones that don't load are http instead of https. Try setting the App Transport Security setting I mentioned in [this comment](https://github.com/uchicago-mobi/MPCS51030-2019-Winter-Forum/issues/74#issuecomment-464734457).

Also let me know if I'm not understanding the issue you're seeing. I was under the impression that you were having trouble getting urls to load in the web view, but that seems to be working...

**Comment by lmnoel** [comment]
<img width="449" alt="screen shot 2019-02-18 at 19 31 38" src="https://user-images.githubusercontent.com/20692394/52984149-db204b00-33b3-11e9-8a6d-8f2d51483590.png">

So I got it to work, but running on my physical iPhone (simulator still doesn't work). I'm fine working with this for now.

I found pages and pages of Stack Overflow complaints about this issue where some people could replicate the issue and others couldn't:
-https://stackoverflow.com/questions/50291678/wkwebview-not-loading-webpage-renders-blank-screen-in-swift
-https://stackoverflow.com/questions/49814149/swift4-wkwebview-warning-of-could-not-signal-service-com-apple-webkit

**Comment by susanstevens** [comment]
OK, glad you got it working on a device! This sounds like a mysterious issue.

**Comment by liuwinshen** [comment]
I'm having the same issue even after the App Transport setting. @susanstevens, may you please take a look? I'd love to get the article to show up. (It used to, but after adding the indicator, it now won't stop loading regardless of the device.)

**Comment by chelseatroy** [comment]
Hey Winshen!

I'll pull down your app and take a look!

**Comment by liuwinshen** [comment]
Thanks, Chelsea! Just pushed up a new commit, but the same issue remains.

**Comment by chelseatroy** [comment]
OK @liuwinshen, it looks like you're missing some constraints on your Web View: X position and width. You can navigate to your Detail View Controller in Storyboard, where you should see a warning about missing constraints. If you click the "Add constraints" button, the web view should work for you!

**Comment by liuwinshen** [comment]
THANK YOU, @chelseatroy !!!!!!!! I had no idea Auto Layout could wreak such havoc. Thank you so much for taking a look at this!
