### ISSUE TITLE
Clarification on "Recent" label requirement

### ISSUE THREAD

**Issue by liuwinshen** [uchicago-mobi/MPCS51030-2019-Winter-Forum#81]
The assignment says: 
> The middle label should display the word “Recent”. This label should only appear if the article was published during the current month.

Does "current month" mean literal month or the last 30 days? For instance, if today were March 1, would the label only appear for articles that were published that day?

**Comment by hbennett766** [comment]
@susanstevens is probably the person to clarify this. It may very well be up to you, as long as you're doing _something_.

FWIW, in office hours, I went through an implementation with a student where we treated it as "current month", so that if today were March 1, the label would only appear for today's articles.

**Comment by susanstevens** [comment]
Good question! I meant current month as in the month we're currently in. So if today were March 1, you would only show the "Recent" label on today's articles.

If you want to show articles published in the last thirty days, that's okay too. The idea is just to get a feel for how a stack view can adjust dynamically when its arranged subviews are shown and hidden.
