### ISSUE TITLE
Recent label appear/disappearing

### ISSUE THREAD

**Issue by jrschaeffer** [uchicago-mobi/MPCS51030-2019-Winter-Forum#86]
I'm working right now on implementing the presence / absence of the "RECENT" label depending on the date of the article.   I am currently doing the date comparison in the `override func tableView(_ ....` method in the `MasterViewController`.   When the app renders each cell for the first time, it properly adds or hides the label...however when I begin to scroll down then back up, I find RECENT labels either disappearing or reappearing.   

I am generating the visibility of RECENT and adjusting constraints programmatically based on this date check, but something tells me I'm doing this too much and it's making the view do wacky things.  

My gut tells me I need to be doing the date check a single time (possibly at the time when I create the `article` object for each element in the API response, instead of every time the cell is rendered... but not sure if I'm running down a rabbit hole or not.  

Appreciate any help!

**Comment by susanstevens** [comment]
One thing to note is that you shouldn’t need to adjust constraints programmatically when you show and hide the label. The magic of stack views is that they will automatically adjust when their subviews are shown and hidden. You should have constraints set on the stack view itself, so that the row height changes dynamically, but not on any of the labels.

Also, you certainly could determine whether the recent label will be shown when you create each article object. But it should also work just fine if you re-run this logic each time the row for the article is shown.

**Comment by jrschaeffer** [comment]
Stackview FTW.   That solves it, thanks.
