### ISSUE TITLE
Gray blank screen in Detail View Controller

### ISSUE THREAD

**Issue by liuwinshen** [uchicago-mobi/MPCS51030-2019-Winter-Forum#90]
I've set up my `UISplitViewControllerDelegate` and the two views appear in portrait and landscape mode on iPads, but my Detail View Controller is grayed out and `viewDidLoad()` is not called upon launching the app. Why might this be the case?

Additionally, I can't get the split view to appear on the iPhone even though it's been working as expected on the iPad. What logic should I review to make sure the views are split for both devices?
![screen shot 2019-02-19 at 6 54 26 pm](https://user-images.githubusercontent.com/35438782/53058289-1ab06b00-3478-11e9-82a9-b9208475da6e.png)
![screen shot 2019-02-19 at 6 54 11 pm](https://user-images.githubusercontent.com/35438782/53058293-1c7a2e80-3478-11e9-869d-cc51a50df6bc.png)

**Comment by susanstevens** [comment]
It looks like the relationship segue from the split view controller to the detail view controller was deleted from your storyboard. If you control drag from the split view controller to the detail view controller, you can select "Detail View Controller" under the "Relationship Segue" options in the pop-up that appears. This should resolve the issue.

When you say the split view doesn't appear on iPhone, do you mean that the master and detail view controllers aren't displaying side by side? If so, this is expected behavior when the iPhone has a compact width. When there isn't a lot of space available horizontally, the master and detail will only appear one at a time, instead of next to each other.

**Comment by liuwinshen** [comment]
Thanks, @susanstevens. I did that so the Master View Controller would appear upon opening the app instead of the Detail View one, but I added it back as you suggested to resolve the gray screen!

And yes, they don't display side-by-side even in landscape mode =( I'll keep working on getting that to happen, since the screenshot in the requirements suggests they should both be viewable when the iPhone is rotated.

**Comment by susanstevens** [comment]
Sounds good! Just to clarify -- master and detail should only display side-by-side on iPhones in landscape mode if the device has "regular width" (as opposed to "compact width") in landscape. For example, master and detail should display side-by-side on iPhone 8 **Plus** in landscape, but not on iPhone 8.

All of this should happen automatically with `UISplitViewController`, unless you modified one of the default settings.

**Comment by liuwinshen** [comment]
Oh! That clarifies it! Thank you =)
