### ISSUE TITLE
Text in table view are overlapping, but will be fine if I click the view.

### ISSUE THREAD

**Issue by lizefei** [uchicago-mobi/MPCS51030-2019-Winter-Forum#96]
The initial search for "apple" will be displayed fine.
But if type in more text, in some cell the text will overlapping, but if I click the cell, the overlapping part will disappear. Is this a bug for my code or the simulator does update the view?
I have called self.NewsTable.reloadData() after search.

![2019-02-19 11 19 52](https://user-images.githubusercontent.com/25712969/53073515-164a7900-349d-11e9-9d10-8b0fd025169a.png)

**Comment by hbennett766** [comment]
This is a code bug. Can you make sure your repo is up to date? I can pull your code down and take a look

**Comment by lizefei** [comment]
> This is a code bug. Can you make sure your repo is up to date? I can pull your code down and take a look

Thank you, my repo is up to date.

**Comment by hbennett766** [comment]
I figured out what's going on here. There are also some other general issues in your master VC.

1. Inside your cellForRowAtIndexPath method, you're manually removing the recent label, which is messing with your stack view. Let the stack view do its job of handling layout for you. Refer to #91 for how to properly manage the recent label.

2. You maintain a class-level `searchActive` boolean. This is unnecessary. It's not actually being used, you just set it to `true` or `false` in a bunch of places. Remove that variable entirely.

3. Your search functionality is too busy, the cells are reloading too quickly and overlapping each other. You have a bunch of delegate methods implemented that only set the now nonexistent `searchActive` variable. Delete all of those methods.

Instead of searching after every text character change, implement the delegate method `func searchBarTextDidEndEditing(_ searchBar: UISearchBar)`. This means a search will only happen after the user is done typing. Move the logic from your `textDidChange` method into this method, and then delete the `textDidChange` method entirely. 

There is a second delegate method to implement here, to make this work. `func searchBarSearchButtonClicked(_ searchBar: UISearchBar)`. Inside this second method, add `searchBar.resignFirstResponder()`. This is a way to trigger the notification that the search bar finished editing.

4. Inside `numberOfRowsInSection`, you're doing extra work, using that `searchActive` Bool. If you haven't already fixed it, just return `news.count`. The search being active doesn't have anything to do with your row count. If `news.count` is 0, then it will be 0.

**Comment by hbennett766** [comment]
Lmk if you have any questions

**Comment by lizefei** [comment]
> Lmk if you have any questions

Thank you, I have fixed all the problem mentioned. There is no overlapping now.
But the table cells in the simulator will be updated (after search) only if I click the simulator(or drag or any touch to it), is this still a bug?

**Comment by hbennett766** [comment]
I'm not sure I understand your question. The expected behavior is that the table view should only update after you tap the search button, not while the user is typing.

**Comment by hbennett766** [comment]
I'll take a look at your code and see if there are any rogue bugs leftover

**Comment by lizefei** [comment]
> I'm not sure I understand your question. The expected behavior is that the table view should only update after you tap the search button, not while the user is typing.

It will not update while I typing now.
But after I finish typing, the view will not be automatically update. Only if I click someway in the simulator, then it will be updated.

**Comment by hbennett766** [comment]
Your search looks great! Nice job on the delegate method fixes. The view will not automatically know that you are done editing. It can't read minds, unfortunately. There has to be a way to tell it that it's done, and to perform the search. You added this delegate method:
```
func searchBarSearchButtonClicked(_ searchBar: UISearchBar){
    searchBar.resignFirstResponder()
}
```
to send that message. This says "once the search button is clicked, I'm done working for now". By resigning the search bar as a first responder, then and only then does your search bar know it's done editing. 

Your stack view update is close, but could be more concise. Your current implementation:
```
if isRecent(news[row].publishedAt!) {
    cell.Recent?.isHidden = false
} else {
    cell.Recent?.isHidden = true
}
```
Instead of explicitly setting `true` or `false`, just set based on the conditional statement itself. Refer to the sample code in #91, and also a general post on Swift Bools in #92. Lmk if this makes sense!

**Comment by lizefei** [comment]
> Your search looks great! Nice job on the delegate method fixes. The view will not automatically know that you are done editing. It can't read minds, unfortunately. There has to be a way to tell it that it's done, and to perform the search. You added this delegate method:
> 
> ```
> func searchBarSearchButtonClicked(_ searchBar: UISearchBar){
>     searchBar.resignFirstResponder()
> }
> ```
> to send that message. This says "once the search button is clicked, I'm done working for now". By resigning the search bar as a first responder, then and only then does your search bar know it's done editing.
> 
> Your stack view update is close, but could be more concise. Your current implementation:
> 
> ```
> if isRecent(news[row].publishedAt!) {
>     cell.Recent?.isHidden = false
> } else {
>     cell.Recent?.isHidden = true
> }
> ```
> Instead of explicitly setting `true` or `false`, just set based on the conditional statement itself. Refer to the sample code in #91, and also a general post on Swift Bools in #92. Lmk if this makes sense!

Problem solve by changing the mentioned if statement to #92. Thank you so much.

**Comment by hbennett766** [comment]
Yeah of course! Glad things got solved 👍🏻

**Comment by lizefei** [comment]
> Yeah of course! Glad things got solved 👍🏻

Sorry, but I still got some overlapping :(.
Is this caused by the constraint I added to stack view in storyboard?
![2019-02-20 8 45 51](https://user-images.githubusercontent.com/25712969/53108557-1a51b780-34ec-11e9-8667-02f1e72a5a09.png)

**Comment by hbennett766** [comment]
@susanstevens @chelseatroy I thought this had something to do with cell reuse, and it might. But I added the override prepareForReuse method to the cell object, reset all the label text to empty strings, and it didn't fix the problem. Might need a fresh set of eyes. Any ideas?

**Comment by lizefei** [comment]
By the way, I am running Xcode 10.1 in macOS 10.13 in VMWare15.0.2, I am not sure whether this is the reason?
